Anand bubbles
MFlowCode/MFC-develop pull request #102
Opened 2022-04-14 03:32 UTC by anandrdbz

Sub-grid bubbles finalized and CuTensor Implementation of WENO

2022-04-14 03:45 UTC, sbryngelson requested changes
i left several comments. can you comment on them and fix some of them before i merge?

2022-04-14 03:45 UTC, sbryngelson commented on src/simulation_code/m_riemann_solvers.fpp
> +                  E_L_acc = gamma_L_acc*pres_L_acc + pi_inf_L_acc + 5d-1*rho_L_acc*vel_L_rms_acc
was this a bug before?

2022-04-14 03:45 UTC, sbryngelson commented on src/simulation_code/m_riemann_solvers.fpp
> +                                Ms_R = max(1d0, SQRT(1d0 + ((5d-1 + gamma_R_acc)/(1d0 + gamma_R_acc))* &
fyi we usually use lower case text for most things in fortran these days.

2022-04-14 03:45 UTC, sbryngelson commented on src/simulation_code/m_riemann_solvers.fpp
> +                                        !nbub_L_acc = (3.d0/(4.d0*pi))*alpha_L_acc(num_fluids)/(0d0 + weight(1)*(R0_L_acc(1)**3d0))
not sure how this strange hard-coding of pi got into the code but thanks for fixing it.

2022-04-14 03:45 UTC, sbryngelson commented on src/simulation_code/m_riemann_solvers.fpp
> +                                        !nbub_R_acc = (3.d0/(4.d0*pi))*alpha_R_acc(num_fluids)/(0d0 + weight(1)*(R0_R_acc(1)**3d0))
these lines are commented out. shall we just delete?

2022-04-14 03:45 UTC, sbryngelson commented on src/simulation_code/m_riemann_solvers.fpp
>                          c_avg_acc = sgm_eps
once you confirm the code works as expected (via tests), we should remove the original CPU code so you don't have `_acc` variables scattered around. in fact, you should probably do the same thing for all the other modules. this will be production code soon and having twice as many variables than we actually use will have to be fixed.

2022-04-14 03:45 UTC, sbryngelson commented on src/simulation_code/m_weno.fpp
> +!$acc end parallel loop
i think these acc directives, i.e, `!$acc parallel` should be text-aligned with the code below them, not at the far left. it makes it easier to read.

2022-04-14 21:35 UTC, anandrdbz commented on src/simulation_code/m_riemann_solvers.fpp
> +                                        !nbub_R_acc = (3.d0/(4.d0*pi))*alpha_R_acc(num_fluids)/(0d0 + weight(1)*(R0_R_acc(1)**3d0))
Yes these can be deleted

2022-04-14 21:36 UTC, anandrdbz commented on src/simulation_code/m_riemann_solvers.fpp
> +                                        !nbub_L_acc = (3.d0/(4.d0*pi))*alpha_L_acc(num_fluids)/(0d0 + weight(1)*(R0_L_acc(1)**3d0))
I was debugging something but yeah it's fixed now so this can be removed as well

2022-04-14 21:36 UTC, anandrdbz commented on src/simulation_code/m_riemann_solvers.fpp
> +                  E_L_acc = gamma_L_acc*pres_L_acc + pi_inf_L_acc + 5d-1*rho_L_acc*vel_L_rms_acc
No, just unnecessary computation, we were taking square root and squaring again, so I fixed it

2022-04-14 21:37 UTC, anandrdbz commented on src/simulation_code/m_riemann_solvers.fpp
> +                                Ms_R = max(1d0, SQRT(1d0 + ((5d-1 + gamma_R_acc)/(1d0 + gamma_R_acc))* &
Okay

2022-04-14 21:37 UTC, anandrdbz commented on src/simulation_code/m_weno.fpp
> +!$acc end parallel loop
I'll shift in the newer commit

2022-04-14 21:39 UTC, anandrdbz commented on src/simulation_code/m_riemann_solvers.fpp
>                          c_avg_acc = sgm_eps
Yeah this is the only module with this most likely, in the other modules only the function names have this suffix. This was done because there were global variables with the same name. I think it can be removed though, I'll check

2022-04-15 04:33 UTC, sbryngelson approved these changes

2022-04-15 04:33 UTC, merged